name: portal-test
version: 1
summary: xdg-desktop-portal test application
description: |
  This test application exercises the features of xdg-desktop-portal

grade: devel
confinement: strict

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604:gnome-3-26-1604

slots:
  portal-test-dbus:
    interface: dbus
    bus: session
    name: org.gnome.PortalTest

apps:
  portal-test:
    command: desktop-launch $SNAP/bin/portal-test
    environment:
      GTK_USE_PORTAL: 1
    desktop: share/applications/org.gnome.PortalTest.desktop
    plugs:
      - desktop
      - desktop-legacy # to quiet a11y complaints
      - gsettings
      - network
      - wayland
      - x11
      - gnome-3-26-1604
    slots:
      - portal-test-dbus

parts:
  gnome-3-26-ppa:
    plugin: nil
    prepare: |
      set -ex
      apt-get install -y software-properties-common
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
      apt-get update
      apt-get dist-upgrade -y

  portal-test:
    build-attributes:
      - no-system-libraries
    after:
      - gnome-3-26-ppa
      - desktop-gnome-platform
    plugin: meson
    source: https://github.com/matthiasclasen/portal-test.git
    meson-parameters:
      - --prefix=/

    build-packages:
      - gcc
      - libgstreamer-plugins-base1.0-dev
      - libgtk-3-dev
