name: portal-test
version: git
license: LGPL-2.1+
summary: xdg-desktop-portal test application
description: |
  This test application exercises the features of xdg-desktop-portal

grade: devel
confinement: strict
base: core18

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804:gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  portal-test-dbus:
    interface: dbus
    bus: session
    name: org.gnome.PortalTest

apps:
  portal-test:
    command: desktop-launch $SNAP/bin/portal-test
    environment:
      GTK_USE_PORTAL: 1
    desktop: share/applications/org.gnome.PortalTest.desktop
    plugs:
      - desktop
      - desktop-legacy # to quiet a11y complaints
      - gsettings
      - network
      - wayland
      - x11
      - gnome-3-28-1804
    slots:
      - portal-test-dbus

parts:
  glib:
    source: https://gitlab.gnome.org/GNOME/glib.git
    #source-branch: glib-2-56
    configflags: [ --prefix=/usr ]
    plugin: autotools
    build-packages:
      - automake
      - autoconf
      - autotools-dev
      - libtool
      - libmount-dev

  desktop-gnome-platform:
    after: [glib]
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
      - libffi-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  portal-test:
    after: [desktop-gnome-platform]
    plugin: meson
    source: https://github.com/matthiasclasen/portal-test.git
    meson-parameters:
      - --prefix=/

    build-packages:
      - gcc
      - libgstreamer-plugins-base1.0-dev
      - libgtk-3-dev
